// <auto-generated />
using HyllieBollCenter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HyllieBollCenter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231220142706_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HyllieBollCenter.Models.DayBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ElevenToThirteenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FifteenToSeventeenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NineToElevenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NineteenToTwentyoneId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeventeenToNineteenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirteenToFifteenId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DayBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
