// <auto-generated />
using System;
using HyllieBollCenter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HyllieBollCenter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231221151819_addsTennisBadmintonAppUser")]
    partial class addsTennisBadmintonAppUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HyllieBollCenter.Models.AppUser", b =>
                {
                    b.Property<string>("StringId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StringId");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("HyllieBollCenter.Models.Badminton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DayBookingId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("DayBookingId");

                    b.ToTable("Badminton");
                });

            modelBuilder.Entity("HyllieBollCenter.Models.DayBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ElevenToThirteenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FifteenToSeventeenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NineToElevenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NineteenToTwentyoneId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeventeenToNineteenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirteenToFifteenId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DayBookings");
                });

            modelBuilder.Entity("HyllieBollCenter.Models.Tennis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DayBookingId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("DayBookingId");

                    b.ToTable("Tennis");
                });

            modelBuilder.Entity("HyllieBollCenter.Models.Badminton", b =>
                {
                    b.HasOne("HyllieBollCenter.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.HasOne("HyllieBollCenter.Models.DayBooking", "DayBooking")
                        .WithMany()
                        .HasForeignKey("DayBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("DayBooking");
                });

            modelBuilder.Entity("HyllieBollCenter.Models.Tennis", b =>
                {
                    b.HasOne("HyllieBollCenter.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.HasOne("HyllieBollCenter.Models.DayBooking", "DayBooking")
                        .WithMany()
                        .HasForeignKey("DayBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("DayBooking");
                });
#pragma warning restore 612, 618
        }
    }
}
